apiVersion: batch/v1
kind: Job
metadata:
  name: secret-spiller
spec:
  template:
    spec:
      containers:
      - name: secret-spiller
        image: dougfish1/spill-it
        env:
        - name: SECRET_TO_SHARE
          valueFrom:
            secretKeyRef:
              name: dougs-secrets
              key: dougsecret2
      restartPolicy: Never
  backoffLimit: 2
